# filename: constants.py
# Last edited: fieryd 24MAY 1254Z
# This file is a list of definitions on physical constants used in the program

atomic_number = dict()

atomic_number["H"] = 1
atomic_number["He"] = 2
atomic_number["Li"] = 3
atomic_number["Be"] = 4
atomic_number["B"] = 5
atomic_number["C"] = 6
atomic_number["N"] = 7
atomic_number["O"] = 8
atomic_number["F"] = 9
atomic_number["Ne"] = 10
atomic_number["Na"] = 11
atomic_number["Mg"] = 12
atomic_number["Al"] = 13
atomic_number["Si"] = 14
atomic_number["P"] = 15
atomic_number["S"] = 16
atomic_number["Cl"] = 17
atomic_number["Ar"] = 18
atomic_number["K"] = 19
atomic_number["Ca"] = 20
atomic_number["Sc"] = 21
atomic_number["Ti"] = 22
atomic_number["V"] = 23
atomic_number["Cr"] = 24
atomic_number["Mn"] = 25
atomic_number["Fe"] = 26
atomic_number["Co"] = 27
atomic_number["Ni"] = 28
atomic_number["Cu"] = 29
atomic_number["Zn"] = 30
atomic_number["Ga"] = 31
atomic_number["Ge"] = 32
atomic_number["As"] = 33
atomic_number["Se"] = 34
atomic_number["Br"] = 35
atomic_number["Kr"] = 36
atomic_number["Rb"] = 37
atomic_number["Sr"] = 38
atomic_number["Y"] = 39
atomic_number["Zr"] = 40
atomic_number["Nb"] = 41
atomic_number["Mo"] = 42
atomic_number["Tc"] = 43
atomic_number["Ru"] = 44
atomic_number["Rh"] = 45
atomic_number["Pd"] = 46
atomic_number["Ag"] = 47
atomic_number["Cd"] = 48
atomic_number["In"] = 49
atomic_number["Sn"] = 50
atomic_number["Sb"] = 51
atomic_number["Te"] = 52
atomic_number["I"] = 53
atomic_number["Xe"] = 54
atomic_number["Cs"] = 55
atomic_number["Ba"] = 56
atomic_number["La"] = 57
atomic_number["Ce"] = 58
atomic_number["Pr"] = 59
atomic_number["Nd"] = 60
atomic_number["Pm"] = 61
atomic_number["Sm"] = 62
atomic_number["Eu"] = 63
atomic_number["Gd"] = 64
atomic_number["Tb"] = 65
atomic_number["Dy"] = 66
atomic_number["Ho"] = 67
atomic_number["Er"] = 68
atomic_number["Tm"] = 69
atomic_number["Yb"] = 70
atomic_number["Lu"] = 71
atomic_number["Hf"] = 72
atomic_number["Ta"] = 73
atomic_number["W"] = 74
atomic_number["Re"] = 75
atomic_number["Os"] = 76
atomic_number["Ir"] = 77
atomic_number["Pt"] = 78
atomic_number["Au"] = 79
atomic_number["Hg"] = 80
atomic_number["Tl"] = 81
atomic_number["Pb"] = 82
atomic_number["Bi"] = 83
atomic_number["Po"] = 84
atomic_number["At"] = 85
atomic_number["Rn"] = 86
atomic_number["Fr"] = 87
atomic_number["Ra"] = 88
atomic_number["Ac"] = 89
atomic_number["Th"] = 90
atomic_number["Pa"] = 91
atomic_number["U"] = 92
atomic_number["Np"] = 93
atomic_number["Pu"] = 94
atomic_number["Am"] = 95
atomic_number["Cm"] = 96
atomic_number["Bk"] = 97
atomic_number["Cf"] = 98
atomic_number["Es"] = 99
atomic_number["Fm"] = 100
atomic_number["Md"] = 101
atomic_number["No"] = 102
atomic_number["Lr"] = 103
atomic_number["Rf"] = 104
atomic_number["Db"] = 105
atomic_number["Sg"] = 106
atomic_number["Bh"] = 107
atomic_number["Hs"] = 108
atomic_number["Mt"] = 109


# Physical constants & unit conversion, copied from psi4

h                         = 6.62606896E-34       # The Planck constant (Js)
c                         = 2.99792458E8         # Speed of light (ms$^{-1}$)
kb                        = 1.3806504E-23        # The Boltzmann constant (JK$^{-1}$)
R                         = 8.314472             # Universal gas constant (JK$^{-1}$mol$^{-1}$)
bohr2angstroms            = 0.52917720859        # Bohr to Angstroms conversion factor
bohr2m                    = 0.52917720859E-10    # Bohr to meters conversion factor
bohr2cm                   = 0.52917720859E-8     # Bohr to centimeters conversion factor
amu2g                     = 1.660538782E-24      # Atomic mass units to grams conversion factor
amu2kg                    = 1.660538782E-27      # Atomic mass units to kg conversion factor
au2amu                    = 5.485799097E-4       # Atomic units (m$@@e$) to atomic mass units conversion factor
hartree2J                 = 4.359744E-18         # Hartree to joule conversion factor
hartree2aJ                = 4.359744             # Hartree to attojoule (10$^{-18}$J) conversion factor
cal2J                     = 4.184                # Calorie to joule conversion factor
dipmom_au2si              = 8.47835281E-30       # Atomic units to SI units (Cm) conversion factor for dipoles
dipmom_au2debye           = 2.54174623           # Atomic units to Debye conversion factor for dipoles
dipmom_debye2si           = 3.335640952E-30      # Debye to SI units (Cm) conversion factor for dipoles
c_au                      = 137.035999679        # Speed of light in atomic units
hartree2ev                = 27.21138             # Hartree to eV conversion factor
hartree2wavenumbers       = 219474.6             # Hartree to cm$^{-1}$ conversion factor
hartree2kcalmol           = 627.5095             # Hartree to kcal mol$^{-1}$ conversion factor
hartree2kJmol             = 2625.500             # Hartree to kilojoule mol$^{-1}$ conversion factor
hartree2MHz               = 6.579684E9           # Hartree to MHz conversion factor
kcalmol2wavenumbers       = 349.7551             # kcal mol$^{-1}$ to cm$^{-1}$ conversion factor
e0                        = 8.854187817E-12      # Vacuum permittivity (Fm$^{-1}$)
na                        = 6.02214179E23        # Avagadro's number
me                        = 9.10938215E-31       # Electron rest mass (in kg)
